### ISSUE TITLE
It's sorting all music into 'Unknown Album Format'

### ISSUE THREAD

**Issue by FrozenCoder1** [EmanDev/gmdr#2]
I have about 250-300 FLAC Files which size about 34 GB and my all files are tagged with correct metadata and covers but it's just sorting all as 'Unknown Album' and 'Unknown Artist' Format

**Comment by EmanDev** [comment]
@FrozenCoder1 
Can you provide me these following info?

1. Windows 10 build version
2. FLAC file sample
3. Does your FLAC files are correctly sorted if you use other music player? - i would understand if you can't provide an answer for this one.

**Comment by EmanDev** [comment]
Closing this since this app doesn't change song tags.
Issue is related to song tag and the way groove music is reading the tags.

**Comment by FrozenCoder1** [comment]
Hey.

**Comment by FrozenCoder1** [comment]
My Tags for all songs are Valid and works like charm in other apps. They Just don't work in Groove music after I resetted the Database.
![2020-11-01 (1)](https://user-images.githubusercontent.com/66153345/97797444-17a4e080-1c43-11eb-9ad6-69a2a23dad12.png)

**Comment by EmanDev** [comment]
> My Tags for all songs are Valid and works like charm in other apps. They Just don't work in Groove music after I resetted the Database.
> ![2020-11-01 (1)](https://user-images.githubusercontent.com/66153345/97797444-17a4e080-1c43-11eb-9ad6-69a2a23dad12.png)

To be honest, this app doesn't fix errors within groove music app, this app only resets database of groove music.
Song tags that doesn't properly appear in the groove music is an issue itself within the groove music.
